apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.apibara.claim }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumes.apibara.storage }}
  storageClassName: {{ .Values.volumes.apibara.class }}
