apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.apibara.name }}
  labels:
    app: {{ .Values.labels.apibara.name }}
spec:
  ports:
    - port: {{ .Values.ports.apibara }}
      targetPort: {{ .Values.ports.apibara }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.labels.apibara.name }}
